#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vulkan-sdk
Version  : 1.0.37.0
Release  : 1
URL      : https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.0.37.0.tar.gz
Source0  : https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/archive/sdk-1.0.37.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause NCSA
Requires: vulkan-sdk-bin
Requires: vulkan-sdk-lib
BuildRequires : beignet-dev
BuildRequires : cmake
BuildRequires : glslang
BuildRequires : mesa-dev
BuildRequires : pkgconfig(OpenCL)
BuildRequires : pkgconfig(gl)
BuildRequires : python3-dev
Patch1: build.patch

%description
Google C++ Testing Framework
============================
http://code.google.com/p/googletest/

%package bin
Summary: bin components for the vulkan-sdk package.
Group: Binaries

%description bin
bin components for the vulkan-sdk package.


%package dev
Summary: dev components for the vulkan-sdk package.
Group: Development
Requires: vulkan-sdk-lib
Requires: vulkan-sdk-bin
Provides: vulkan-sdk-devel

%description dev
dev components for the vulkan-sdk package.


%package lib
Summary: lib components for the vulkan-sdk package.
Group: Libraries

%description lib
lib components for the vulkan-sdk package.


%prep
%setup -q -n Vulkan-LoaderAndValidationLayers-sdk-1.0.37.0
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484493897
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DBUILD_WSI_MIR_SUPPORT=OFF -DBUILD_TESTS=OFF -DBUILD_VKJSON=OFF -DBUILD_LAYERS=OFF
make VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1484493897
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/vulkaninfo

%files dev
%defattr(-,root,root,-)
/usr/include/vulkan/vk_icd.h
/usr/include/vulkan/vk_layer.h
/usr/include/vulkan/vk_platform.h
/usr/include/vulkan/vk_sdk_platform.h
/usr/include/vulkan/vulkan.h
/usr/include/vulkan/vulkan.hpp
/usr/lib64/libvulkan.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvulkan.so.1
/usr/lib64/libvulkan.so.1.0.37
